version: '3.5'

networks:
  backend:
    driver: bridge

services:
  screen-shot:
      image: registry.cn-shenzhen.aliyuncs.com/t4tstudio/screen-shot:latest
      container_name: screen-shot
      environment:
        - ALIOSS_REGION=
        - ALIOSS_ACCESS_KEY_ID=
        - ALIOSS_ACCESS_KEY_SECRET=
        - ALIOSS_BUCKET=
      networks:
        - backend